project:
  render: 
    - "*.qmd"
    - "!code/"
  type: website
  output-dir: docs
  preview: 
    watch-inputs: false

website:
  title: "F1-race-predictions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Predictions
        href: honors/outcomes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



